select*from customers limit 10;

ALTER TABLE customers 
CHANGE `Purchase Amount (USD)` purchase_amount INT;

describe customers;

#1. WHAT is the total revenue generated by male vs female customers?

select gender , SUM(purchase_amount) as revenue 
from customers 
group by gender; 
 
#2. which customers used a discount but still spent more that the average purchase amount?

select customer_id, gender, purchase_amount 
from customers
where discount_applied = "Yes" and purchase_amount >= (select AVG(purchase_amount) from customers);

#3 which are the top 5 prouducts with the highest average review rating 

select item_purchased, round(AVG(review_rating),2) as "average product rating"
from customers 
group by item_purchased
order by avg(review_rating) desc;

#4 compare the avg purchase amount between standard and express shipping 

select shipping_type, 
round(avg(purchase_amount),2)
from customers
where shipping_type in ("Standard" , "Express")
group by shipping_type

#5  highest items purachased 
SELECT item_purchased, COUNT(*) AS total_count
FROM customers 
GROUP BY item_purchased
order by total_count desc ;

#6 do subscribed customers spend more ?compare average spend and total revenue between subscribers and non subscribers 
select subscription_status, count(customer_id) as total_customers , AVG(purchase_amount)as avg_spend, sum(purchase_amount) as total_revenue 
from customers 
group by subscription_status ;

#7  which 5 products have the highest percentage of pruchases with discounts applied 

select item_purchased, round(100*sum(CASE WHEN discount_applied="Yes" THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from customers 
group by item_purchased
order by discount_rate desc 
limit 5;

#8 segment customers into new, returing and loyalbased on thier total number of pervious purchaces, and show the count of each segment 
with customer_type as(select customer_id, previous_purchases, 
CASE
WHEN previous_purchases=1 THEN "New"
WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
ELSE "Loyal"
END AS customer_segment
from customers
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

#9 what are the top 3 most purchased products within each category 
SELECT item_purchased, category, total_purchased
FROM (
    SELECT 
        item_purchased,
        category,
        COUNT(*) AS total_purchased,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rank_num
    FROM customers
    GROUP BY category, item_purchased
) AS ranked
WHERE rank_num <= 3;

#10 Arew customers who are repeat buyers more than 5 previuos purchases also likely to subscribe?
select subscription_status,
count(customer_id)as repeat_buyers 
from customers
where previous_purchases>5 
group by subscription_status;

#11 what is teh revenue contribution of each age group 

select age_group, sum(purchase_amount) as revenue
from customers
group by age_group
order by revenue desc; 


